### PR TITLE
Added in the WP_User object to the wp_login hook. 

### PR DESCRIPTION
**Pull request by RaybirdDesigns**
This requires 2 arguments to be sent, and fixes the WooCommerce login issue.

### CODE REVIEW

**Comment by aaronpk** [comment]
Can you please provide a link to docs on how this fixes it?

**Comment by RaybirdDesigns** [comment]
@aaronpk 
This is the hook reference for wp_login: https://developer.wordpress.org/reference/hooks/wp_login/

It requests 2 params, the user_login as a string, and a WP_User object.

And this is the WooCommerce function that hooks into wp_login: https://docs.woocommerce.com/wc-apidocs/source-function-wc_maybe_store_user_agent.html#802-815

Because this hooks into wp_login, the user_login string and user Object are both required, even though it's only the object being utilised

**Comment by aaronpk** [comment]
Thank you!

**Comment by RaybirdDesigns** [comment]
@aaronpk no problem at all mate

**Pull request merged**
