### PR TITLE
Add Settings Page

### LINKED ISSUE #2: Provide an admin UI to configure the Okta settings
* client_id
* client_secret
* okta domain
* authorization server ID

### PR DESCRIPTION
**Pull request by omarchehab98**
Hello Aaron,

I implemented the settings page to allow users to configure the plugin without leaving WordPress (Closes #2).

When activating the plugin from a new installation, the plugin does not take over the login until it is configured from the **Settings > Okta Sign-In Widget** page.

Once the administrator configures the environment, the plugin takes over the login and present the Okta Widget on login.

Regards,
Omar Chehab

Okta Sign-In Widget Settings Menu

Okta Sign-In Widget Settings Page

### CODE REVIEW

**Comment by omarchehab98** [comment]
If you would like me to implement backward compatibility, then I can modify the initialization of `OktaSignIn` to optionally use the `env.php` file as an override over the options.

Also, if the `env.php` file exists, the options page should show a message containing something along the lines of: "Options are currently being overridden by the `env.php` file.".

Note that the option fields should not be disabled to allow administrators to migrate to using the options page without downtime.

**Comment by aaronpk** [comment]
Thanks! This is great. I do like the idea of backwards compatibility support, just in case anyone has deployed this and goes to update their code.

Also I realized we forgot to add a `contributing.md` file to this repo. It would help me out if you could agree to release your contributions to the public domain. Can you confirm that's okay? Thanks!

**Comment by omarchehab98** [comment]
I agree to release my contributions to the public domain

**Comment by aaronpk** [comment]
Thank you for this! I ended up making some other updates and pulled in your changes manually.

**Pull request closed without merging**
